### ISSUE TITLE
Ranking Report - How to execute this scenario

### ISSUE THREAD

**Issue by junpaolo** [junpaolo/ePrice-validation-testing#49]
Hi Vernon,

I want to clarify how to execute this one from the Developer Notebook - Web Site Page96

![error message availble list](https://cloud.githubusercontent.com/assets/20081753/17829014/86ae4f5a-66d2-11e6-9c63-f11bf2642503.png)

Pls. advise thanks

**Comment by vernonminer** [comment]
To display an error on the "Selected" list side is difficult for this criterion because even though it is marked as required the OR condition overrides that requirement. If you select no price list and no price list group and click the submit button the required error is displayed on the "Selected" side of the price list not the price list group. 

To display an error on the "Available" list side is even harder to simulate. An error in creating the list from the database should display on the "Available" list side.

For the documentation images I edited the JavaScript for the page to _showModelError for the appropriate list item.

Because the display of the error requires manipulation outside normal application operations I would suggest not including a test case for this.

**Comment by junpaolo** [comment]
Thank you for clarifying this sir. We will just consider this as out of scope
